version: '3'

services: 
  web:
    image: nginx
    volumes: 
      - ./nginx/app.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on: 
      - my_app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    ports:
      - 5432

  my_app:
    image: guisalmeida/app-crud-nginx-pgsql:latest
    build: .
    depends_on:
      - db